## Reminder: Logistic Regression

### Hypothesis
$$ H(X) = \frac{1}{1+e^{-W^T X}} $$

### Cost

$$ cost(W) = -\frac{1}{m} \sum y \log\left(H(x)\right) + (1-y) \left( \log(1-H(x) \right) $$

 - If $y \simeq H(x)$, cost is near 0.
 - If $y \neq H(x)$, cost is high.

### Weight Update via Gradient Descent

$$ W := W - \alpha \frac{\partial}{\partial W} cost(W) $$

 - $\alpha$: Learning rate



---



## 데이터 로드

In [0]:
import torch                  # pytorch
import torch.optim as optim   # optim라이브러리의 SGD(최적화 알고리즘)을 사용

torch.manual_seed(1) # For reproducibility 씨드고정.

# 임의 데이터 생성
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]


#numpy리스트데이터를 torch알고리즘을 사용하기 위해 tensor로 변환
x_train = torch.FloatTensor(x_data) 
y_train = torch.FloatTensor(y_data)

print(x_data)   # numpy list데이터
print(x_train)  # tensor 데이터     어떻게 다른지 눈으로 비교.

# print(x_train.shape)
# print(y_train.shape)

[[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
tensor([[1., 2.],
        [2., 3.],
        [3., 1.],
        [4., 3.],
        [5., 3.],
        [6., 2.]])
torch.Size([6, 2])
torch.Size([6, 1])


## 모델 학습

In [0]:
# 모델 초기화
# 입력데이터(x) 는     2개
# 출력(Y)는 0 or 1로 1개.   --> binary classification
# 따라서 W=(2,1) 

W = torch.zeros((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산   
                # sigmode 함수 사용하여 예측값을 0~1로 bound
    hypothesis = torch.sigmoid(x_train.matmul(W) + b) # or .mm or @
    cost = -(y_train * torch.log(hypothesis) + 
             (1 - y_train) * torch.log(1 - hypothesis)).mean()  #에러평균

    # cost로 H(x) 개선
    optimizer.zero_grad()  #optimizer의 gradient를 0으로 초기화.
    cost.backward()        #cost를 계산하고 이를 이용해 optimizer알고리즘을 수행.
    optimizer.step()       # w를 갱신.

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))


# 에폭=1000  cost= 0.019852
# 에폭=10000 Cost: 0.002132
# 에폭=100000 cost : nan. 

Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.134722
Epoch  200/1000 Cost: 0.080643
Epoch  300/1000 Cost: 0.057900
Epoch  400/1000 Cost: 0.045300
Epoch  500/1000 Cost: 0.037261
Epoch  600/1000 Cost: 0.031673
Epoch  700/1000 Cost: 0.027556
Epoch  800/1000 Cost: 0.024394
Epoch  900/1000 Cost: 0.021888
Epoch 1000/1000 Cost: 0.019852


## 데이터 평가

- 학습한 w가 y데이터(실제 y데이터)를 나타내고 있는지 평가하기.


In [0]:
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
print(hypothesis[:5])    # 0과 1로 나타나지 않음. sigmoid를 통해 0~1사이의 값으로 bound해놨음.

#0.5를 기준으로 true(1), false(0) 로 매핑
prediction = hypothesis >= torch.FloatTensor([0.5])  
print(prediction[:5])     # w>0.5 true.  w<0.5 false

print(y_train[:5])

# prediction과 실제 y데이터를 비교하기.
# 일치하면 True, 일치하지 않으면 False.
correct_prediction = prediction.float() == y_train  
print(correct_prediction[:5])

# 정확도.
accuracy = correct_prediction.sum().item() / len(correct_prediction)
print('The model has an accuracy of {:2.2f}% for the training set.'.format(accuracy * 100))

tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01]], grad_fn=<SliceBackward>)
tensor([[False],
        [False],
        [False],
        [ True],
        [ True]])
tensor([[False],
        [False],
        [False],
        [ True],
        [ True]])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.]])
tensor([[True],
        [True],
        [True],
        [True],
        [True]])
The model has an accuracy of 100.00% for the training set.


In [0]:
# 결과 예측하기
 
# 새로운데이터.XX= 100시간 공부, 5번수업참가.
# --> TRUE.  (=합격).

XX = [[100, 5]]
xx = torch.FloatTensor(XX);
hypothesis = torch.sigmoid(xx.matmul(W) + b)
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)




tensor([[True]])
