## 퍼셉트론이란? 
- 은닉레이어가 하나인 신경망 구조

## 퍼셉트론과 XOR
- XOR 문제를 해결할 수 없다.



---



#### pytorch 라이브러리 보기
https://pytorch.org/docs/stable/index.html

### 데이터 입출력 정의



In [ ]:
# CPU 모드
import torch

In [ ]:
torch.manual_seed(777)  #랜덤 씨드를 고정시켜서 매번 값이 같게 나오도록한다.

In [ ]:
X = torch.FloatTensor([[0,0], [0,1], [1,0],[1,1]])
Y = torch.FloatTensor([[0],[1],[1],[0]])

In [ ]:
X

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])

In [ ]:
Y

tensor([[0.],
        [1.],
        [1.],
        [0.]])

### NN 모델 정의

In [ ]:
# 모델 정의
# Layer 정의

# torch.nn.Linear : 한 개의 logistic regression 
# (2,1,bias=True) : 2개의 입력 -> 1개의 출력을 의미.

linear = torch.nn.Linear(2,1,bias=True) # Fully Connected Layer
sigmoid = torch.nn.Sigmoid() 

In [ ]:
model = torch.nn.Sequential(linear,sigmoid)  #linear와 sigmoid를 연결

In [ ]:
model

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
  (1): Sigmoid()
)

### 모델 학습

In [ ]:
# 모델 학습 환경 설정: loss function, optimizer설정 등등

loss = torch.nn.BCELoss()   # Binary Cross Entropy Loss
optimizer = torch.optim.SGD(model.parameters(),lr=1)    #모델의 파리미터를 학습, lr=1


In [ ]:
for stop in range(10000):
    
    # 그래디언트 초기화
    optimizer.zero_grad()
    # Forward 계산
    hypothesis = model(X)       # 예측값 y를 구함.

    # Error 계산
    cost = loss(hypothesis, Y)  # 예측값과 실제 y값의 차이.에러
    # Backward 계산 
    cost.backward()             # backward를 계산
    # 가중치 갱신
    optimizer.step()            # 에러를 기준으로 w,b를 갱신

    if stop % 100 == 0:
        print(stop, cost.item())


0 0.7273974418640137
100 0.6931476593017578
200 0.6931471824645996
300 0.6931471824645996
400 0.6931471824645996
500 0.6931471824645996
600 0.6931471824645996
700 0.6931471824645996
800 0.6931471824645996
900 0.6931471824645996
1000 0.6931471824645996
1100 0.6931471824645996
1200 0.6931471824645996
1300 0.6931471824645996
1400 0.6931471824645996
1500 0.6931471824645996
1600 0.6931471824645996
1700 0.6931471824645996
1800 0.6931471824645996
1900 0.6931471824645996
2000 0.6931471824645996
2100 0.6931471824645996
2200 0.6931471824645996
2300 0.6931471824645996
2400 0.6931471824645996
2500 0.6931471824645996
2600 0.6931471824645996
2700 0.6931471824645996
2800 0.6931471824645996
2900 0.6931471824645996
3000 0.6931471824645996
3100 0.6931471824645996
3200 0.6931471824645996
3300 0.6931471824645996
3400 0.6931471824645996
3500 0.6931471824645996
3600 0.6931471824645996
3700 0.6931471824645996
3800 0.6931471824645996
3900 0.6931471824645996
4000 0.6931471824645996
4100 0.6931471824645996
4200

### 모델 평가

#### --> 퍼셉트론에서는 XOR문제를 해결할 수 없으므로 어떤 방법을 사용해도 정확도는 1이 나오지 않는다.

In [ ]:
## w,b 평가

# required_grad = true는 학습중임을 의미.
# required_grad = false 모델을 평가중임을 의미. 학습하지 않음. 

with torch.no_grad(): # 임시로 required_grad = false로 설정하는 것과 같다.

    hypothesis = model(X)
    predicted = (hypothesis > 0.5).float()    # 1 or 0으로 바꾸기
    accuracy = (predicted == Y).float().mean()  
    print('\n Hypothesis: ', hypothesis.numpy(), '\n Correct: ', predicted.numpy(), '\n Accuracy: ', accuracy.item())

# 퍼셉트론에서는 XOR문제를 해결할 수 없으므로 어떤 방법을 사용해도 정확도는 1이 나오지 않는다.


 Hypothesis:  [[0.5]
 [0.5]
 [0.5]
 [0.5]] 
 Correct:  [[0.]
 [0.]
 [0.]
 [0.]] 
 Accuracy:  0.5


In [ ]:
predicted

tensor([[0.],
        [0.],
        [0.],
        [0.]])