In [ ]:
!pip uninstall -y kaggle
!pip install --upgrade pip
!pip install kaggle==1.5.6

Uninstalling kaggle-1.5.6:
  Successfully uninstalled kaggle-1.5.6
     |████████████████████████████████| 1.5MB 4.7MB/s 
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1
     |████████████████████████████████| 58 kB 2.5 MB/s 
  Created wheel for kaggle: filename=kaggle-1.5.6-py3-none-any.whl size=72859 sha256=294c54a39ea978b118ed5742a127f8fe3dd045206d7d5d04ab15edaa5b67f6d4
  Stored in directory: /root/.cache/pip/wheels/01/3e/ff/77407ebac3ef71a79b9166a8382aecf88415a0bcbe3c095a01
Successfully built kaggle


In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json
!kaggle -v

Kaggle API 1.5.6


In [ ]:
!kaggle competitions download -c city-commercialchange-analysis

!unzip city-commercialchange-analysis.zip

  0% 0.00/7.99k [00:00<?, ?B/s]
100% 7.99k/7.99k [00:00<00:00, 8.14MB/s]
Archive:  city-commercialchange-analysis.zip
  inflating: submit.csv              
  inflating: test.csv                
  inflating: train.csv               


In [ ]:
import torch
import torchvision.datasets as data
import torchvision.transforms as transforms
import random

In [ ]:
import numpy as np
import torch
import torch.optim as optim
import pandas as pd

xy=pd.read_csv('train.csv')
xy

year  quarter  ...  Closing months_Average  Commercial change
0    2016        1  ...                1.062500                  0
1    2019        4  ...                1.037037                  0
2    2015        4  ...                1.000000                  2
3    2019        4  ...                1.055556                  2
4    2014        2  ...                0.933333                  3
..    ...      ...  ...                     ...                ...
546  2017        2  ...                0.960000                  3
547  2019        4  ...                0.925926                  3
548  2016        3  ...                1.040816                  2
549  2018        1  ...                1.000000                  3
550  2014        3  ...                1.044444                  0

[551 rows x 8 columns]

In [ ]:
corr=xy.corr(method='pearson')
corr

year  ...  Commercial change
year                      1.000000  ...          -0.010037
quarter                  -0.011769  ...          -0.005533
city                      0.012068  ...           0.387811
Operating months          0.467735  ...          -0.712853
Closing months            0.685062  ...          -0.575557
Operating months_Average -0.018703  ...          -0.814984
Closing months_Average   -0.024846  ...          -0.801290
Commercial change        -0.010037  ...           1.000000

[8 rows x 8 columns]

In [ ]:
x_data=xy.iloc[:,0:7]    #0~7 col
y_data=xy.iloc[:,7]

x_data

year  quarter  ...  Operating months_Average  Closing months_Average
0    2016        1  ...                  1.031250                1.062500
1    2019        4  ...                  1.009091                1.037037
2    2015        4  ...                  0.968421                1.000000
3    2019        4  ...                  0.954545                1.055556
4    2014        2  ...                  0.989130                0.933333
..    ...      ...  ...                       ...                     ...
546  2017        2  ...                  0.938144                0.960000
547  2019        4  ...                  0.854545                0.925926
548  2016        3  ...                  0.989583                1.040816
549  2018        1  ...                  0.990000                1.000000
550  2014        3  ...                  1.010753                1.044444

[551 rows x 7 columns]

In [ ]:
y_data

0      0
1      0
2      2
3      2
4      3
      ..
546    3
547    3
548    2
549    3
550    0
Name: Commercial change, Length: 551, dtype: int64

In [ ]:
x_train=np.array(x_data)
y_train=np.array(y_data)

x_train=torch.FloatTensor(x_train)
y_train=torch.LongTensor(y_train)

x_train[:5]

tensor([[2.0160e+03, 1.0000e+00, 1.1290e+04, 9.9000e+01, 5.1000e+01, 1.0312e+00,
         1.0625e+00],
        [2.0190e+03, 4.0000e+00, 1.1290e+04, 1.1100e+02, 5.6000e+01, 1.0091e+00,
         1.0370e+00],
        [2.0150e+03, 4.0000e+00, 1.1380e+04, 9.2000e+01, 4.8000e+01, 9.6842e-01,
         1.0000e+00],
        [2.0190e+03, 4.0000e+00, 1.1200e+04, 1.0500e+02, 5.7000e+01, 9.5455e-01,
         1.0556e+00],
        [2.0140e+03, 2.0000e+00, 1.1260e+04, 9.1000e+01, 4.2000e+01, 9.8913e-01,
         9.3333e-01]])

In [ ]:
x_train.shape

torch.Size([551, 7])

In [ ]:
y_train.shape

torch.Size([551])

In [ ]:
y_train

tensor([0, 0, 2, 2, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 0, 3, 3, 3, 3, 2, 3, 0, 3, 3,
        3, 0, 0, 0, 2, 1, 0, 0, 3, 3, 3, 3, 0, 0, 0, 3, 3, 3, 0, 3, 3, 0, 0, 3,
        3, 0, 0, 3, 0, 3, 0, 0, 0, 2, 3, 1, 3, 1, 0, 0, 0, 1, 0, 0, 3, 3, 1, 3,
        0, 3, 3, 0, 0, 3, 3, 3, 3, 3, 1, 3, 3, 1, 3, 0, 3, 3, 3, 0, 3, 3, 3, 0,
        3, 0, 0, 0, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 0, 3, 1, 3, 3, 3, 0, 3, 3,
        3, 0, 2, 2, 3, 3, 0, 3, 1, 0, 2, 0, 1, 3, 3, 3, 3, 3, 3, 3, 1, 3, 1, 3,
        3, 0, 3, 1, 2, 3, 3, 3, 3, 3, 0, 0, 3, 3, 0, 3, 3, 3, 2, 0, 1, 3, 3, 0,
        3, 3, 3, 1, 0, 0, 3, 0, 3, 3, 3, 3, 3, 3, 0, 3, 0, 3, 3, 3, 3, 3, 3, 0,
        3, 0, 2, 3, 0, 0, 2, 3, 3, 0, 0, 3, 2, 3, 0, 0, 3, 3, 2, 2, 3, 2, 3, 3,
        3, 0, 0, 2, 0, 3, 0, 3, 3, 1, 3, 0, 3, 3, 3, 1, 0, 0, 1, 1, 0, 3, 3, 0,
        2, 2, 0, 3, 3, 3, 0, 3, 0, 0, 1, 3, 3, 0, 0, 3, 0, 0, 1, 3, 1, 1, 0, 3,
        3, 1, 2, 0, 3, 3, 3, 3, 3, 0, 3, 2, 3, 0, 3, 3, 3, 0, 0, 3, 0, 3, 3, 3,
        3, 0, 3, 3, 3, 3, 3, 3, 1, 0, 0,

1) linear regression

In [ ]:
import torch.nn.functional as F

nb_class=4
nb_data = len(y_train)

W=torch.zeros((7,nb_class), requires_grad=True)
b=torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W,b], lr=1)

nb_epochs=10000
for epoch in range(nb_epochs+1):
  
  hypothesis = F.softmax(x_train.matmul(W)+b, dim=1)

  y_one_hot=torch.zeros(nb_data, nb_class)
  y_one_hot.scatter_(1,y_train.unsqueeze(1),1)

  cost=(y_one_hot * -torch.log(F.softmax(hypothesis, dim=1))).sum(dim=1).mean()

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 1000==0:
    print('Epoch {:4d}/{} cost: {:.6f} '.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/10000 cost: 1.386295 
Epoch 1000/10000 cost: 1.199204 
Epoch 2000/10000 cost: 1.199204 
Epoch 3000/10000 cost: 1.199204 
Epoch 4000/10000 cost: 1.199204 
Epoch 5000/10000 cost: 1.199204 
Epoch 6000/10000 cost: 1.199204 
Epoch 7000/10000 cost: 1.199204 
Epoch 8000/10000 cost: 1.199204 
Epoch 9000/10000 cost: 1.199204 
Epoch 10000/10000 cost: 1.199204 


In [ ]:
test=pd.read_csv('test.csv')

x_test=test.to_numpy()
x_test=torch.FloatTensor(x_test)

hypothesis=F.softmax(x_test.matmul(W)+b, dim=1)
predict=torch.argmax(hypothesis, dim=1)

predict

tensor([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], grad_fn=<NotImplemented>)

In [ ]:
solution=pd.read_csv('solution.csv')
y_test=solution.iloc[:,1]

y_test=y_test.to_numpy()
y_test=torch.LongTensor(y_test)
y_test

tensor([3, 0, 0, 0, 3, 0, 0, 1, 3, 0, 0, 3, 3, 0, 3, 0, 3, 0, 0, 3, 0, 0, 0, 3,
        0, 0, 3, 3, 0, 0, 0, 3, 0, 3, 3, 3, 1, 0, 3, 3, 1, 1, 3, 3, 0, 3, 3, 3,
        3, 3, 0, 0, 3, 3, 2, 3, 3, 3, 3, 1, 3, 0])

In [ ]:
correct = predict == y_test
accuracy=correct.float().mean()

print('Accuracy:', accuracy.item())

Accuracy: 0.5


### 3layer 
- xavier init
- Adam
- hidden layer node 개수: 512
- 학습 파라미터 설정
  learning_rate = 0.01
  training_epochs = 15
  batch_size = 100
-> Accuracy: 0.5483871102333069

### training epoch과 hidden layer node 개수 변경
- training_epochs = 55
- hidden layer node 개수: 256

-> Accuracy: 0.725806474685669

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

random.seed(777)
torch.manual_seed(777)
if device == 'cuda':
  torch.cuda.manual_seed_all(777)

In [ ]:
# 학습 파라미터 설정
learning_rate = 0.01
training_epochs = 55
batch_size = 100

In [ ]:

train = torch.utils.data.TensorDataset(x_train, y_train)

In [ ]:
data_loader = torch.utils.data.DataLoader(dataset=train,
                                          batch_size=batch_size,
                                          shuffle=True,
                                          drop_last=True)
#xy=train

In [ ]:
# 3-Layer

linear1 = torch.nn.Linear(7,256,bias=True)
linear2 = torch.nn.Linear(256,256,bias=True)
linear3 = torch.nn.Linear(256,4,bias=True)
relu = torch.nn.ReLU()

In [ ]:
# Random Init => Xavier Init
torch.nn.init.xavier_normal_(linear1.weight)
torch.nn.init.xavier_normal_(linear2.weight)
torch.nn.init.xavier_normal_(linear3.weight)

Parameter containing:
tensor([[ 0.0191,  0.0337,  0.0226,  ..., -0.0312, -0.0489, -0.0005],
        [-0.0130,  0.0307, -0.0692,  ..., -0.0873, -0.1966,  0.0183],
        [-0.0366,  0.0039, -0.0539,  ...,  0.1732, -0.0786, -0.0262],
        [-0.0586, -0.1101, -0.1071,  ..., -0.0391,  0.0904, -0.0184]],
       requires_grad=True)

In [ ]:
model = torch.nn.Sequential(linear1,relu,linear2,relu,linear3).to(device)

In [ ]:
# 손실함수와 최적화 함수
loss = torch.nn.CrossEntropyLoss().to(device) # softmax 내부적으로 계산
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate) 

In [ ]:

total_batch = len(data_loader)
for epoch in range(training_epochs):
    avg_cost = 0

    for X, Y in data_loader:

        # one-hot encoding되어 있지 않음
        Y = Y.to(device)
        #%debug

        # 그래디언트 초기화
        optimizer.zero_grad()
        # Forward 계산
        hypothesis = model(X)
        # Error 계산
        cost = loss(hypothesis, Y)
        # Backparopagation
        cost.backward()
        # 가중치 갱신
        optimizer.step()

        # 평균 Error 계산
        avg_cost += cost / total_batch

    print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))

print('Learning finished')

Epoch: 0001 cost = 4618.148437500
Epoch: 0002 cost = 634.161987305
Epoch: 0003 cost = 403.280487061
Epoch: 0004 cost = 285.489440918
Epoch: 0005 cost = 87.098579407
Epoch: 0006 cost = 59.655490875
Epoch: 0007 cost = 46.773086548
Epoch: 0008 cost = 30.862031937
Epoch: 0009 cost = 22.525419235
Epoch: 0010 cost = 30.513933182
Epoch: 0011 cost = 21.525777817
Epoch: 0012 cost = 18.017164230
Epoch: 0013 cost = 9.530428886
Epoch: 0014 cost = 9.234341621
Epoch: 0015 cost = 6.006206512
Epoch: 0016 cost = 3.274038792
Epoch: 0017 cost = 4.619340420
Epoch: 0018 cost = 4.316328526
Epoch: 0019 cost = 3.867229223
Epoch: 0020 cost = 2.192936182
Epoch: 0021 cost = 2.100803614
Epoch: 0022 cost = 1.767905354
Epoch: 0023 cost = 1.586549759
Epoch: 0024 cost = 1.418062210
Epoch: 0025 cost = 1.452842236
Epoch: 0026 cost = 1.245497465
Epoch: 0027 cost = 1.203593969
Epoch: 0028 cost = 1.209717274
Epoch: 0029 cost = 1.141152382
Epoch: 0030 cost = 1.083192348
Epoch: 0031 cost = 1.102835059
Epoch: 0032 cost = 1.0

In [ ]:
test=pd.read_csv('test.csv')

with torch.no_grad():
  x_test=test.loc[:,:]
  x_test=np.array(x_test)
  x_test=torch.from_numpy(x_test).float().to(device)

  prediction=model(x_test)
  prediction = torch.argmax(prediction, 1)

prediction

tensor([3, 0, 0, 3, 3, 3, 0, 3, 3, 0, 0, 3, 3, 0, 3, 0, 3, 0, 3, 3, 0, 3, 3, 3,
        0, 3, 3, 3, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0])

In [ ]:
# prediction = prediction.cpu().numpy().reshape(-1,1)

In [ ]:
solution=pd.read_csv('solution.csv')
y_test=solution.iloc[:,1]
y_test

0     3
1     0
2     0
3     0
4     3
     ..
57    3
58    3
59    1
60    3
61    0
Name: Label, Length: 62, dtype: int64

In [ ]:
y_test=y_test.to_numpy()
y_test=torch.LongTensor(y_test)
y_test

tensor([3, 0, 0, 0, 3, 0, 0, 1, 3, 0, 0, 3, 3, 0, 3, 0, 3, 0, 0, 3, 0, 0, 0, 3,
        0, 0, 3, 3, 0, 0, 0, 3, 0, 3, 3, 3, 1, 0, 3, 3, 1, 1, 3, 3, 0, 3, 3, 3,
        3, 3, 0, 0, 3, 3, 2, 3, 3, 3, 3, 1, 3, 0])

In [ ]:
correct = prediction == y_test
accuracy=correct.float().mean()

print('Accuracy:', accuracy.item())

Accuracy: 0.725806474685669


In [ ]:
submit = pd.read_csv('submit.csv')
submit

ID  Label
0    0      0
1    1      0
2    2      0
3    3      0
4    4      0
..  ..    ...
57  57      0
58  58      0
59  59      0
60  60      0
61  61      0

[62 rows x 2 columns]

In [ ]:
id=np.array([i for i in range(62)]).reshape(-1,1)
prediction=prediction.reshape(-1,1)

result=np.hstack([id, prediction])
df=pd.DataFrame(result, columns=['ID','Label'])
df.to_csv('baseline.csv', index=False, header=True)

result

array([[ 0,  3],
       [ 1,  0],
       [ 2,  0],
       [ 3,  3],
       [ 4,  3],
       [ 5,  3],
       [ 6,  0],
       [ 7,  3],
       [ 8,  3],
       [ 9,  0],
       [10,  0],
       [11,  3],
       [12,  3],
       [13,  0],
       [14,  3],
       [15,  0],
       [16,  3],
       [17,  0],
       [18,  3],
       [19,  3],
       [20,  0],
       [21,  3],
       [22,  3],
       [23,  3],
       [24,  0],
       [25,  3],
       [26,  3],
       [27,  3],
       [28,  0],
       [29,  0],
       [30,  3],
       [31,  3],
       [32,  3],
       [33,  3],
       [34,  3],
       [35,  3],
       [36,  3],
       [37,  3],
       [38,  3],
       [39,  3],
       [40,  3],
       [41,  3],
       [42,  3],
       [43,  3],
       [44,  3],
       [45,  3],
       [46,  3],
       [47,  3],
       [48,  3],
       [49,  3],
       [50,  3],
       [51,  0],
       [52,  3],
       [53,  3],
       [54,  3],
       [55,  3],
       [56,  3],
       [57,  3],
       [58,  3

### layer수를 변경해보기

#### 2) 5layer
- Xavier Init
- Adam 
- 학습 파라미터 동일.
- hidden layer의 노드개수 256

-> accuracy: 0.5
- 오히려 감소했다.

3) 5layer dropout

->  0.4516128897666931
- 더 감소..



3)번 수정하면서 변화 확인하기
-  hidden layer의 노드수를 256 -> 512 변경
- epoch 변경
- 4layer로 수정 
-> 모두 accuracy 차이 x

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

random.seed(777)
torch.manual_seed(777)
if device == 'cuda':
  torch.cuda.manual_seed_all(777)

In [ ]:
# 학습 파라미터 설정
learning_rate = 0.01
training_epochs = 15
batch_size = 100
drop_prob = 0.3

In [ ]:
data_loader = torch.utils.data.DataLoader(dataset=train,
                                          batch_size=batch_size,
                                          shuffle=True,
                                          drop_last=True)


In [ ]:
# 5-layer, node 512개

linear1 = torch.nn.Linear(7,512,bias=True)
linear2 = torch.nn.Linear(512,512,bias=True)
linear3 = torch.nn.Linear(512,512,bias=True)
linear4 = torch.nn.Linear(512,512,bias=True)
linear5 = torch.nn.Linear(512,4,bias=True)
relu = torch.nn.ReLU()
dropout = torch.nn.Dropout(p=drop_prob)

In [ ]:
# Random Init => Xavier Init
torch.nn.init.xavier_normal_(linear1.weight)
torch.nn.init.xavier_normal_(linear2.weight)
torch.nn.init.xavier_normal_(linear3.weight)
torch.nn.init.xavier_normal_(linear4.weight)
torch.nn.init.xavier_normal_(linear5.weight)

Parameter containing:
tensor([[ 0.0339,  0.0071, -0.0097,  ...,  0.1105, -0.0747,  0.0206],
        [ 0.0766, -0.0139,  0.0103,  ..., -0.0071, -0.0481,  0.0749],
        [ 0.0902, -0.0071,  0.0309,  ..., -0.0588,  0.0051,  0.0301],
        [ 0.0328,  0.0503,  0.0254,  ...,  0.0017, -0.0767,  0.0686]],
       requires_grad=True)

In [ ]:
model = torch.nn.Sequential(linear1,relu,dropout,
                            linear2,relu,dropout,
                            linear3,relu,dropout,
                            linear4,relu,dropout,
                            linear5).to(device)

In [ ]:
# 손실함수와 최적화 함수
loss = torch.nn.CrossEntropyLoss().to(device) # softmax 내부적으로 계산
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate) 

In [ ]:

total_batch = len(data_loader)
model.train()                   #

for epoch in range(training_epochs):
    avg_cost = 0

    for X, Y in data_loader:

        # one-hot encoding되어 있지 않음
        Y = Y.to(device)
        #%debug

        # 그래디언트 초기화
        optimizer.zero_grad()
        # Forward 계산
        hypothesis = model(X)
        # Error 계산
        cost = loss(hypothesis, Y)
        # Backparopagation
        cost.backward()
        # 가중치 갱신
        optimizer.step()

        # 평균 Error 계산
        avg_cost += cost / total_batch

    print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))

print('Learning finished')

Epoch: 0001 cost = 8011.513183594
Epoch: 0002 cost = 86.645294189
Epoch: 0003 cost = 14.006909370
Epoch: 0004 cost = 4.441485405
Epoch: 0005 cost = 1.798620939
Epoch: 0006 cost = 1.500811815
Epoch: 0007 cost = 1.315311670
Epoch: 0008 cost = 1.272233129
Epoch: 0009 cost = 1.277658701
Epoch: 0010 cost = 1.268587232
Epoch: 0011 cost = 1.246531725
Epoch: 0012 cost = 1.206743360
Epoch: 0013 cost = 1.179470778
Epoch: 0014 cost = 1.192618728
Epoch: 0015 cost = 1.162581921
Learning finished


In [ ]:
with torch.no_grad():
  model.eval() 
  x_test=test.loc[:,:]
  x_test=np.array(x_test)
  x_test=torch.from_numpy(x_test).float().to(device)

  prediction=model(x_test)
  prediction = torch.argmax(prediction, 1)
  
  print(prediction)

tensor([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])


In [ ]:
correct = prediction == y_test
accuracy=correct.float().mean()

print('Accuracy:', accuracy.item())

Accuracy: 0.5
